# NumPy
The core library for scientific computing in Python. It is useful for multidimensional array objects.

## Index
* [Creating Arrays](#Creating-Arrays)
    * [Reshaping Arrays](#Reshaping-Arrays)
    * [Array Indexing](#Array-Indexing)
* [Datatypes](#Datatypes)
* [Array Math](#Array-Math)
    * [Random Numbers](#Random-Numbers)
* [Copy & View](#Copy-&-View)
    * [Array Copy](#Array-Copy)
    * [Array View](#Array-View)
    * [Checking Array Ownership](#Checking-Array-Ownership)
* [Array Iterating](#Array-Iterating)


### References
* [Python NumPy Tutorial (with Jupyter & Colab)](https://cs231n.github.io/python-numpy-tutorial/#numpy)
* [Numpy Array Slicing](https://www.w3schools.com/python/numpy_array_slicing.asp)

## Creating Arrays
Numpy arrays are a grid of values, indexed by a tuple of non-negative integers.
* Rank: Number of dimensions
* Shape: Size of the array along with each dimension (row, col)

In [1]:
import numpy as np

a = np.array([1, 2, 3])  # creates a rank 1 array
print(a.shape)
print(a[0], a[1], a[2])

print()

b = np.array([[1, 2, 3], [4, 5, 6]])  # creates a rank 2 array
print(b.shape)  # prints (rows, cols)
print(b[0,0], b[0,1], b[1,0])

(3,)
1 2 3

(2, 3)
1 2 4


Below are some functions to create different types of arrays...

In [2]:
a = np.zeros((2, 2))  # creates an array of all zeros
print('Zero Array:\n', a)

print()

b = np.ones((1, 2))  # creates an array of all ones
print('Array of ones:\n', b)

print()

c = np.full((2, 2), 7)  # creates a constant array of 7's
print('Constant array of sevens:\n', c)

print()

d = np.eye(2)  # creates a 2x2 identity matrix
print('Identity matrix', d)

print()

e = np.random.random((2, 2))  # creates array of random values
print(e)

Zero Array:
 [[0. 0.]
 [0. 0.]]

Array of ones:
 [[1. 1.]]

Constant array of sevens:
 [[7 7]
 [7 7]]

Identity matrix [[1. 0.]
 [0. 1.]]

[[0.47473492 0.46458353]
 [0.97220258 0.84043518]]


### Reshaping Arrays
You can alter the number of elements in each dimension using the `reshape` attribute

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newArr = arr.reshape(4, 3) # reshapes arr into 4rows, 3cols

print('Original Array:\n', arr, '\n')
print('Reshaped Array:\n', newArr)

print('\nReshaping into the third dimension...')
newArr = arr.reshape(2, 3, 2)  # creates 2 arrays, each with 3 arrays containing 2 elements
print(newArr)

# Flattening the array
print('\nFlattening the third dimension...')
flatArr = newArr.reshape(-1)  # converting multidimensional arr into 1D
print(flatArr)

Original Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12] 

Reshaped Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Reshaping into the third dimension...
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

Flattening the third dimension...
[ 1  2  3  4  5  6  7  8  9 10 11 12]


### Array Indexing
**Slicing**: Just like lists in Python, numpy arrays can be sliced.
* We pass slices like: `[start : end]`

In [4]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])  # slices starting at index 1, ending at index 4 (excludes index 5)

print(arr[4:])  # slices elements from index 4 to the end of arr (includes index 4)

print(arr[:4])  # slices elements from start of arr to index 3 (excludes index 4)

[2 3 4 5]
[5 6 7]
[1 2 3 4]


**Notice how the results *includes* the start index, but *excludes* the end index.**

In [5]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

print()

# remember: (row, col)
b = a[:2, 1:3]  # slices first 2 rows, between col indexes 1-2
print(b)

print()

c = a[1, 1:4]  # slices index row 1, between col indexes 1-3
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[2 3]
 [6 7]]

[6 7 8]


**Step**: Using the `step` value determines the step of the slicing.
* We can define the step, like: [start:end:step]

In [6]:
print(arr)
print(arr[::2])  # slices every other element from the entire array
print(arr[1:5:2])  # slices every other element from index 1 to index 5

[1 2 3 4 5 6 7]
[1 3 5 7]
[2 4]


## Datatypes
Every numpy array uses elements of the same type and chooses the datatype when an array is created.

In [7]:
x = np.array([1, 2])
print(x, x.dtype)

x = np.array([1.5, 2.2])
print(x, x.dtype)

[1 2] int64
[1.5 2.2] float64


You can also force a specific datatype using the `dtype=` argument:

In [8]:
x = np.array([1.1, 2.5], dtype=np.int64)
print(x, x.dtype)

[1 2] int64


## Array Math
Mathematical functions operate elementwise, and are available as operator overloads and functions in numpy.

In [9]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)

print('Operator sum:\n', x + y)  # operator sums x[0,0] + y[0,0], and so on
print('Function sum:\n',np.add(x, y)) # function version

print()

print('Operator difference:\n', x - y)  # operator version
print('Function difference:\n',np.subtract(x, y)) # function version

print()

print('Operator product:\n', x * y)  # operator version
print('Function product:\n',np.multiply(x, y)) # function version

print()

print('Operator quotient:\n', x / y)  # operator version
print('Function quotient:\n',np.divide(x, y)) # function version

Operator sum:
 [[ 6.  8.]
 [10. 12.]]
Function sum:
 [[ 6.  8.]
 [10. 12.]]

Operator difference:
 [[-4. -4.]
 [-4. -4.]]
Function difference:
 [[-4. -4.]
 [-4. -4.]]

Operator product:
 [[ 5. 12.]
 [21. 32.]]
Function product:
 [[ 5. 12.]
 [21. 32.]]

Operator quotient:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
Function quotient:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


The `sum` function sums an array of elements over a given axis:

In [10]:
x = np.array([[1,2], [3,4]])
print(np.sum(x))  # sums all elements
print(np.sum(x, axis=0))  # sum of each col
print(np.sum(x, axis=1))  # sum of each row

10
[4 6]
[3 7]


The `dot` function computes inner products of vectors, to multiply a cevtor by a matrix, and to multiply matrices.

In [11]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

v = np.array([9, 10])
w = np.array([11, 12])

print('Matrices:\n',x,y)
print()
print('Vectors:\n',v,w)
print()

# inner product of vectors
print('Vector * Vector')
print(v.dot(w))  # instance method version
print(np.dot(v, w))  # numpy function version
print()

# matrix/vector product
print('Matrix * Vector')
print(x.dot(v))  # instance method version
print(np.dot(x,v))  # numpy function version
print()

# matrix/matrix product
print('Matrix * Matrix')
print(x.dot(y))  # instance method version
print(np.dot(x,y))  # numpy function version

Matrices:
 [[1 2]
 [3 4]] [[5 6]
 [7 8]]

Vectors:
 [ 9 10] [11 12]

Vector * Vector
219
219

Matrix * Vector
[29 67]
[29 67]

Matrix * Matrix
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### Random Numbers
Importing numpys `random` module allows your to work with random numbers.

In [12]:
from numpy import random

x = random.randint(100)  # generate random int
print(x)

x = random.rand()  # generate random float from 0-1
print(x)

print()
# Random used on arrays
x = random.randint(100, size=(5))  # generate 5 element array w/ random ints from 0-100
print(x)
print()

x = random.randint(100, size=(3, 5))  # generate array with 3rows,5cols w/random ints from 0-100
print(x)
print()

63
0.35895008147249874

[90 85 52 54 31]

[[35 17 54 97 40]
 [30 60 93 35 39]
 [23 44 23  0 68]]



The `choice()` method takes an array as a parameter and randomly returns one of the values.

In [13]:
x = random.choice([5,7,9,3,12])
print(x)

7


## Copy & View
Copying an array lets you create a new array.

Viewing an array lets you view the original array.

### Array Copy
The copy *owns* the data. Any changes to the copy does not affect the original array. Any changes made to the original array do not affect the copy.

In [14]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()

print('Array: ', arr)
print('Copy: ', x)

print('\nChanging some numbers...beep boop\n')

arr[3] = 64
x[0] = 42
print('Array: ', arr)
print('Copy: ', x)

Array:  [1 2 3 4 5]
Copy:  [1 2 3 4 5]

Changing some numbers...beep boop

Array:  [ 1  2  3 64  5]
Copy:  [42  2  3  4  5]


### Array View
The view *does not* own the data. Any changes made to the view will affect the original array. Any changes made to the original array will affect the view.

In [15]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()

print('Array: ', arr)
print('Viewing Array: ', x)

print('\nChanging some numbers...beep boop\n')

arr[3] = 64
x[0] = 42
print('Array: ', arr)
print('Viewing Array: ', x)

Array:  [1 2 3 4 5]
Viewing Array:  [1 2 3 4 5]

Changing some numbers...beep boop

Array:  [42  2  3 64  5]
Viewing Array:  [42  2  3 64  5]


### Checking Array Ownership
Numpy has the `base` attribute that returns `None` if the array owns the data. If the array does *not* own the data, returns the original array. 

In [16]:
arr = np.array([1, 2, 3, 4, 5])  # original arr
x = arr.copy()  # owns
y = arr.view()  # does not own

print(x.base)
print(y.base)

None
[1 2 3 4 5]


## Array Iterating

In [17]:
# iterating 1D array
print('1 dimensional iteration')
arr = np.array([1,2,3,4,5])
for i in arr:
    print(i)

print()

# iterating 2D array
print('2 dimensional iterations')
arr = np.array([[1,2,3], [4,5,6]])
for i in arr:
    print(i)
# iterating each scalar element of 2D array
arr = np.array([[1,2,3], [4,5,6]])
for i in arr:
    for j in i:
        print(j)

print()

# iterating 3D array
print('3 dimensional iterations')
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
for i in arr:
    print(i)
# iterating each scalar element of 3D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for i in arr:
  for j in i:
    for k in j:
      print(k)
print()

1 dimensional iteration
1
2
3
4
5

2 dimensional iterations
[1 2 3]
[4 5 6]
1
2
3
4
5
6

3 dimensional iterations
[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]
1
2
3
4
5
6
7
8
9
10
11
12

